language: c
os:
  - linux
  - osx
arch:
  - amd64
  # - ppc64le  # Apply patch
  - arm64

install: ci-base/install.sh travis sysbench
script: ./run.sh
jobs:
  exclude:
  - os: osx
    arch: ppc64le
  - os: osx
    arch: arm64
